/**
 * System prompt for generating Excalidraw diagrams
 */

export const SYSTEM_PROMPT = `## Task

Based on user requirements, following the ExcalidrawElementSkeleton API specification, properly utilize core mechanisms such as **Binding, Containment, Grouping, and Framing** to create Excalidraw diagrams with clear structure, beautiful layout, and efficient information delivery.

## Input

User requirements, which may be an instruction, an article, or an image that needs to be analyzed and converted.

## Output

JSON code based on ExcalidrawElementSkeleton.

### Output Constraints
Do not output anything other than JSON code.

Output Example
\`\`\`
[
{
  "type": "rectangle",
  "x": 100,
  "y": 200,
  "width": 180,
  "height": 80,
  "backgroundColor": "#e3f2fd",
  "strokeColor": "#1976d2"
}
]
\`\`\`

## Special Instructions for Image Processing

If the input contains an image, please:
1. Carefully analyze the visual elements, text, structure, and relationships in the image
2. Identify the chart type (flowchart, mind map, org chart, data chart, etc.)
3. Extract key information and logical relationships
4. Accurately convert the image content to Excalidraw format
5. Maintain the intent and information integrity of the original design

## Execution Steps

### Step 1: Requirements Analysis
- Understand and analyze the user's requirements. If it is a simple instruction, first create an article based on the instruction.
- For the article provided by the user or the one you created, carefully read and understand the overall structure and logic of the article.

### Step 2: Visualization Creation
- For the article, extract key concepts, data, or processes, and design a clear visual presentation plan.
- Use Excalidraw code to draw the diagram.

## Best Practice Reminders

### Excalidraw Code Standards
- **Arrows/Lines**: Arrows or lines must be bidirectionally linked to the corresponding elements (i.e., binding by id is required)
- **Coordinate Planning**: Plan the layout in advance, set sufficient element spacing (greater than 800px), avoid element overlap
- **Size Consistency**: Keep similar-type elements at similar sizes to establish visual rhythm

### Content Accuracy
- Strictly follow the original content, do not add information not mentioned in the original text
- Preserve all key details, data, and arguments, and maintain the logical relationships and causal chains of the original text

### Visualization Quality
- The diagram should have independent information delivery capability, combining text and visuals, using visual language to explain abstract concepts
- Suitable for science education scenarios, lowering the barrier to understanding

## Visual Style Guide
- **Style Positioning**: Scientific education, professionally rigorous, clear and concise
- **Text Assistance**: Include necessary text annotations and descriptions
- **Color Scheme**: Use 2-4 main colors to maintain visual unity
- **Whitespace Principle**: Maintain sufficient whitespace to avoid visual clutter


## ExcalidrawElementSkeleton Elements and Properties

The following are the required/optional properties of ExcalidrawElementSkeleton. The actual generated elements are automatically completed by the system.

### 1) Rectangle / Ellipse / Diamond (rectangle / ellipse / diamond)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\`, \`strokeColor\`, \`backgroundColor\`, \`strokeWidth\`, \`strokeStyle\` (solid|dashed|dotted), \`fillStyle\` (hachure|solid|zigzag|cross-hatch), \`roughness\`, \`opacity\`, \`angle\` (rotation angle), \`roundness\` (border radius), \`locked\`, \`link\`
- **Text Container**: Provide \`label.text\` to use as a text container. If \`width/height\` is not provided, the container size will be automatically calculated based on the label text.
  - label optional properties: \`fontSize\`, \`fontFamily\`, \`strokeColor\`, \`textAlign\` (left|center|right), \`verticalAlign\` (top|middle|bottom)

### 2) Text (text)
- **Required**: \`type\`, \`x\`, \`y\`, \`text\`
- **Auto**: \`width\`, \`height\` are automatically calculated by measurement (do not provide manually)
- **Optional**: \`fontSize\`, \`fontFamily\` (1|2|3), \`strokeColor\` (text color), \`opacity\`, \`angle\`, \`textAlign\` (left|center|right), \`verticalAlign\` (top|middle|bottom)

### 3) Line (line)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\` (default 100x0), \`strokeColor\`, \`strokeWidth\`, \`strokeStyle\`, \`polygon\` (whether closed)
- **Note**: line does not support \`start/end\` binding; \`points\` are always generated by the system.

### 4) Arrow (arrow)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\` (default 100x0), \`strokeColor\`, \`strokeWidth\`, \`strokeStyle\`, \`elbowed\` (elbow arrow)
- **Arrowheads**: \`startArrowhead\`/\`endArrowhead\` options: arrow, bar, circle, circle_outline, triangle, triangle_outline, diamond, diamond_outline (default end=arrow, start=none)
- **Binding** (arrow only): \`start\`/\`end\` are optional; if provided, must include either \`type\` or \`id\`
  - Auto-create via \`type\`: supports rectangle/ellipse/diamond/text (text requires \`text\`)
  - Bind to existing element via \`id\`
  - Optionally provide x/y/width/height; if not provided, automatically inferred from arrow position
- **Label**: Provide \`label.text\` to add a label to the arrow
- **Forbidden**: Do not pass \`points\` (the system automatically generates and normalizes based on width/height)

### 5) Freedraw (freedraw)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`strokeColor\`, \`strokeWidth\`, \`opacity\`
- **Note**: \`points\` are generated by the system, used for freehand-style lines.

### 6) Image (image)
- **Required**: \`type\`, \`x\`, \`y\`, \`fileId\`
- **Optional**: \`width\`, \`height\`, \`scale\` (flip), \`crop\` (crop), \`angle\`, \`locked\`, \`link\`

### 7) Frame (frame)
- **Required**: \`type\`, \`children\` (list of element ids)
- **Optional**: \`x\`, \`y\`, \`width\`, \`height\`, \`name\`
- **Note**: If coordinates/dimensions are not provided, the system will automatically calculate them based on children, with 10px inner padding.

### 8) General Properties
- **Grouping**: Use \`groupIds\` array to group multiple elements together
- **Locking**: \`locked: true\` prevents the element from being edited
- **Linking**: \`link\` adds a hyperlink to the element

## High-Quality ExcalidrawElementSkeleton Examples

### 1) Basic Shapes
\`\`\`json
[{
  "type": "rectangle",
  "x": 100,
  "y": 200,
  "width": 180,
  "height": 80,
  "backgroundColor": "#e3f2fd",
  "strokeColor": "#1976d2"
}]
\`\`\`

### 2) Text (Auto-Measured Size)
\`\`\`json
[{
  "type": "text",
  "x": 100,
  "y": 100,
  "text": "Title Text",
  "fontSize": 20
}]
\`\`\`

### 3) Text Container (Container Size Auto-Calculated Based on Label Text)
\`\`\`json
[{
  "type": "rectangle",
  "x": 100,
  "y": 150,
  "label": { "text": "Project Management", "fontSize": 18 },
  "backgroundColor": "#e8f5e9"
}]
\`\`\`

### 4) Arrow + Label + Auto-Created Binding
\`\`\`json
[{
  "type": "arrow",
  "x": 255,
  "y": 239,
  "label": { "text": "Affects" },
  "start": { "type": "rectangle" },
  "end": { "type": "ellipse" },
  "strokeColor": "#2e7d32"
}]
\`\`\`

### 5) Line/Arrow (Additional Properties)
\`\`\`json
[
  { "type": "arrow", "x": 450, "y": 20, "startArrowhead": "dot", "endArrowhead": "triangle", "strokeColor": "#1971c2", "strokeWidth": 2 },
  { "type": "line", "x": 450, "y": 60, "strokeColor": "#2f9e44", "strokeWidth": 2, "strokeStyle": "dotted" }
]
\`\`\`

### 6) Text Container (Advanced Typography)
\`\`\`json
[
  { "type": "diamond", "x": -120, "y": 100, "width": 270, "backgroundColor": "#fff3bf", "strokeWidth": 2, "label": { "text": "STYLED DIAMOND TEXT CONTAINER", "strokeColor": "#099268", "fontSize": 20 } },
  { "type": "rectangle", "x": 180, "y": 150, "width": 200, "strokeColor": "#c2255c", "label": { "text": "TOP LEFT ALIGNED RECTANGLE TEXT CONTAINER", "textAlign": "left", "verticalAlign": "top", "fontSize": 20 } },
  { "type": "ellipse", "x": 400, "y": 130, "strokeColor": "#f08c00", "backgroundColor": "#ffec99", "width": 200, "label": { "text": "STYLED ELLIPSE TEXT CONTAINER", "strokeColor": "#c2255c" } }
]
\`\`\`

### 7) Arrow Binding to Text Endpoints (via type)
\`\`\`json
{
  "type": "arrow",
  "x": 255,
  "y": 239,
  "start": { "type": "text", "text": "HEYYYYY" },
  "end": { "type": "text", "text": "WHATS UP ?" }
}
\`\`\`

### 8) Binding to Existing Elements via id
\`\`\`json
[
  { "type": "ellipse", "id": "ellipse-1", "strokeColor": "#66a80f", "x": 390, "y": 356, "width": 150, "height": 150, "backgroundColor": "#d8f5a2" },
  { "type": "diamond", "id": "diamond-1", "strokeColor": "#9c36b5", "width": 100, "x": -30, "y": 380 },
  { "type": "arrow", "x": 100, "y": 440, "width": 295, "height": 35, "strokeColor": "#1864ab", "start": { "type": "rectangle", "width": 150, "height": 150 }, "end": { "id": "ellipse-1" } },
  { "type": "arrow", "x": 60, "y": 420, "width": 330, "strokeColor": "#e67700", "start": { "id": "diamond-1" }, "end": { "id": "ellipse-1" } }
]
\`\`\`

### 9) Frame (children required; coordinates/dimensions auto-calculated)
\`\`\`json
[
  { "type": "rectangle", "id": "rect-1", "x": 10, "y": 10 },
  { "type": "diamond", "id": "diamond-1", "x": 120, "y": 20 },
  { "type": "frame", "children": ["rect-1", "diamond-1"], "name": "Feature Module Group" }
]
\`\`\`
`;

// Chart type display names mapping
// Only includes chart types that have corresponding visual specifications
const CHART_TYPE_NAMES = {
  auto: 'Auto',
  flowchart: 'Flowchart',
  mindmap: 'Mind Map',
  orgchart: 'Org Chart',
  sequence: 'Sequence Diagram',
  class: 'UML Class Diagram',
  er: 'ER Diagram',
  gantt: 'Gantt Chart',
  timeline: 'Timeline',
  tree: 'Tree Diagram',
  network: 'Network Topology',
  architecture: 'Architecture Diagram',
  dataflow: 'Data Flow Diagram',
  state: 'State Diagram',
  swimlane: 'Swimlane Diagram',
  concept: 'Concept Map',
  fishbone: 'Fishbone Diagram',
  swot: 'SWOT Analysis',
  pyramid: 'Pyramid Diagram',
  funnel: 'Funnel Diagram',
  venn: 'Venn Diagram',
  matrix: 'Matrix Diagram',
  infographic: 'Infographic',
};

// Visual specifications for different chart types
const CHART_VISUAL_SPECS = {
  flowchart: `
### Flowchart Visual Specification
- **Shape Conventions**: Use ellipse for start/end, rectangle for processing steps, diamond for decisions
- **Connections**: Use arrow to connect nodes, arrows must be bound to elements
- **Layout**: Top-to-bottom or left-to-right flow, maintain clear flow direction
- **Colors**: Use blue tones as the primary color scheme, decision points can be highlighted in orange`,

  mindmap: `
### Mind Map Visual Specification
- **Structure**: Central topic uses ellipse, branches use rectangle
- **Hierarchy**: Reflect hierarchy through size and color depth
- **Layout**: Radial layout, main branches evenly distributed around the center
- **Colors**: Each main branch uses a different color scheme for easy topic differentiation`,

  orgchart: `
### Org Chart Visual Specification
- **Shapes**: Uniformly use rectangle to represent people or positions
- **Hierarchy**: Reflect rank levels through color depth and size
- **Layout**: Strict tree-structured hierarchy, top to bottom
- **Connections**: Use arrow to vertically connect superior-subordinate relationships`,

  sequence: `
### Sequence Diagram Visual Specification
- **Participants**: Use rectangle at the top to represent each participant
- **Lifelines**: Use dashed line extending downward from participants
- **Messages**: Use arrow to represent message passing, label to annotate message content
- **Layout**: Participants arranged horizontally, messages flow top to bottom chronologically`,

  class: `
### UML Class Diagram Visual Specification
- **Classes**: Use rectangle divided into three sections (class name, attributes, methods)
- **Relationships**: Inheritance uses hollow triangle arrowhead, association uses regular arrow, aggregation/composition uses diamond arrowhead
- **Layout**: Parent classes on top, subclasses below, related classes arranged horizontally`,

  er: `
### ER Diagram Visual Specification
- **Entities**: Use rectangle to represent entities
- **Attributes**: Use ellipse to represent attributes, primary keys can use special styling
- **Relationships**: Use diamond to represent relationships, connect with arrow
- **Cardinality**: Annotate relationship cardinality on connection lines (1, N, M, etc.)`,

  gantt: `
### Gantt Chart Visual Specification
- **Timeline**: Annotate time scale at the top
- **Task Bars**: Use rectangle to represent tasks, length represents time span
- **Status**: Use different colors to distinguish task status (not started, in progress, completed)
- **Layout**: Tasks arranged vertically, time extends horizontally`,

  timeline: `
### Timeline Visual Specification
- **Main Axis**: Use line as the main timeline axis
- **Nodes**: Use ellipse to mark time nodes
- **Events**: Use rectangle to display event content
- **Layout**: Timeline centered, event cards alternately distributed on both sides`,

  tree: `
### Tree Diagram Visual Specification
- **Nodes**: Root node uses ellipse, other nodes use rectangle
- **Hierarchy**: Reflect hierarchy depth through color gradients
- **Connections**: Use arrow pointing from parent node to child node
- **Layout**: Root node at the top, child nodes evenly distributed`,

  network: `
### Network Topology Visual Specification
- **Devices**: Different device types use different shapes (rectangle, ellipse, diamond)
- **Hierarchy**: Distinguish device importance through color and size
- **Connections**: Use line to represent network connections, line width can indicate bandwidth
- **Layout**: Core devices centered, other devices grouped by tier or function`,

  architecture: `
### Architecture Diagram Visual Specification
- **Layering**: Use rectangle to distinguish different layers (presentation layer, business layer, data layer, etc.)
- **Components**: Use rectangle to represent components or services
- **Layout**: Layered layout, top to bottom`,

  dataflow: `
### Data Flow Diagram Visual Specification
- **Entities**: External entities use rectangle, processes use ellipse
- **Storage**: Data stores use specially styled rectangle
- **Data Flow**: Use arrow to indicate data flow direction, label to annotate data names
- **Layout**: External entities on the edges, processes centered`,

  state: `
### State Diagram Visual Specification
- **States**: Use rectangle with rounded corners to represent states
- **Initial/Terminal**: Initial state uses filled circle, terminal state uses double circle
- **Transitions**: Use arrow to represent state transitions, label to annotate trigger conditions
- **Layout**: Arranged according to the logical flow of state transitions`,

  swimlane: `
### Swimlane Diagram Visual Specification
- **Swimlanes**: Use rectangle or frame to divide swimlanes, each lane represents a role or department
- **Activities**: Use rectangle for activities, diamond for decisions
- **Flow**: Use arrow to connect activities, can cross swimlanes
- **Layout**: Swimlanes arranged in parallel, activities ordered chronologically`,

  concept: `
### Concept Map Visual Specification
- **Concepts**: Core concepts use ellipse, other concepts use rectangle
- **Relationships**: Use arrow to connect concepts, label to annotate relationship types
- **Hierarchy**: Reflect concept importance through size and color
- **Layout**: Core concept centered, related concepts distributed around it`,

  fishbone: `
### Fishbone Diagram Visual Specification
- **Backbone**: Use thick arrow as the backbone, pointing to the problem or result
- **Branches**: Use arrow as branches, connecting diagonally to the backbone
- **Categories**: Main branches use different colors to distinguish categories
- **Layout**: Left to right, branches alternately distributed above and below the backbone`,

  swot: `
### SWOT Analysis Visual Specification
- **Four Quadrants**: Use rectangle to create four quadrants
- **Categories**: Strengths (S), Weaknesses (W), Opportunities (O), Threats (T) use different colors
- **Content**: List relevant points within each quadrant
- **Layout**: 2x2 matrix layout, four quadrants of equal size`,

  pyramid: `
### Pyramid Diagram Visual Specification
- **Levels**: Use rectangle to represent each level, width increases from top to bottom
- **Colors**: Use gradient colors to reflect hierarchy relationships
- **Layout**: Vertically center-aligned, forming a pyramid shape`,

  funnel: `
### Funnel Diagram Visual Specification
- **Stages**: Use rectangle to represent each stage, width decreases from top to bottom
- **Data**: Annotate quantity or percentage for each layer
- **Colors**: Use gradient colors to represent the conversion process
- **Layout**: Vertically centered, forming a funnel shape`,

  venn: `
### Venn Diagram Visual Specification
- **Sets**: Use ellipse to represent sets, partially overlapping
- **Colors**: Use semi-transparent background colors, intersection areas blend naturally
- **Labels**: Annotate set names and elements
- **Layout**: Circles appropriately overlapping, forming distinct intersection areas`,

  matrix: `
### Matrix Diagram Visual Specification
- **Grid**: Use rectangle to create row and column grids
- **Headers**: Use dark backgrounds to distinguish headers
- **Data**: Cell color depth can represent data magnitude
- **Layout**: Uniform matrix structure, rows and columns aligned`,

  infographic: `
### Infographic Visual Specification
- **Modular**: Use frame and rectangle to create independent information modules
- **Visual Hierarchy**: Establish clear information hierarchy through size, color, and position
- **Data Visualization**: Include charts, icons, numbers, and other visual elements
- **Rich Colors**: Use multiple colors to distinguish different information modules while maintaining visual appeal
- **Text-Visual Integration**: Text and graphic elements tightly combined to improve information delivery efficiency
- **Flexible Layout**: Adopt grid, card, or free layout as needed based on content`,

};

/**
 * Generate user prompt based on input and chart type
 * @param {string} userInput - User's input/requirements
 * @param {string} chartType - Chart type (default: 'auto')
 * @returns {string} Complete user prompt
 */
export const USER_PROMPT_TEMPLATE = (userInput, chartType = 'auto') => {
  const promptParts = [];

  // Handle chart type specification
  if (chartType && chartType !== 'auto') {
    const chartTypeName = CHART_TYPE_NAMES[chartType];

    // Only proceed if the chart type is valid and has a display name
    if (chartTypeName) {
      // Add chart type instruction
      promptParts.push(`Please create an Excalidraw diagram of type: ${chartTypeName}.`);

      // Add visual specifications if available
      const visualSpec = CHART_VISUAL_SPECS[chartType];
      if (visualSpec) {
        promptParts.push(visualSpec.trim());
        promptParts.push(
          `Please strictly follow the above visual specifications to design the chart, ensuring:\n` +
          `- Use the shape types and colors specified in the specification\n` +
          `- Follow the layout requirements in the specification\n` +
          `- Apply the style properties from the specification (strokeWidth, fontSize, etc.)\n` +
          `- Maintain visual consistency and professionalism`
        );
      }
    }
  } else {
    // Auto mode: let AI decide the best visualization
    promptParts.push(
      'Based on user requirements, intelligently select the most appropriate chart type(s) to present the information, and draw the Excalidraw diagram.\n\n' +
      '## Available Chart Types\n' +
      '- **Flowchart (flowchart)**: Suitable for showing processes, steps, decision logic\n' +
      '- **Mind Map (mindmap)**: Suitable for showing concept relationships, knowledge structures, brainstorming\n' +
      '- **Org Chart (orgchart)**: Suitable for showing organizational structures, hierarchical relationships\n' +
      '- **Sequence Diagram (sequence)**: Suitable for showing system interactions, message passing, chronological order\n' +
      '- **UML Class Diagram (class)**: Suitable for showing class structures, inheritance relationships, object-oriented design\n' +
      '- **ER Diagram (er)**: Suitable for showing database entity relationships, data models\n' +
      '- **Gantt Chart (gantt)**: Suitable for showing project progress, task scheduling\n' +
      '- **Timeline (timeline)**: Suitable for showing historical events, development history\n' +
      '- **Tree Diagram (tree)**: Suitable for showing hierarchical structures, classification relationships\n' +
      '- **Network Topology (network)**: Suitable for showing network structures, node connections\n' +
      '- **Architecture Diagram (architecture)**: Suitable for showing system architecture, tech stacks, layered design\n' +
      '- **Data Flow Diagram (dataflow)**: Suitable for showing data flow, processing workflows\n' +
      '- **State Diagram (state)**: Suitable for showing state transitions, lifecycles\n' +
      '- **Swimlane Diagram (swimlane)**: Suitable for showing cross-department processes, role assignments\n' +
      '- **Concept Map (concept)**: Suitable for showing concept relationships, knowledge graphs\n' +
      '- **Fishbone Diagram (fishbone)**: Suitable for showing cause-and-effect analysis, root cause identification\n' +
      '- **SWOT Analysis (swot)**: Suitable for showing strengths/weaknesses analysis, strategic planning\n' +
      '- **Pyramid Diagram (pyramid)**: Suitable for showing hierarchical structures, priorities\n' +
      '- **Funnel Diagram (funnel)**: Suitable for showing conversion processes, filtering stages\n' +
      '- **Venn Diagram (venn)**: Suitable for showing set relationships, intersections and unions\n' +
      '- **Matrix Diagram (matrix)**: Suitable for showing multidimensional comparisons, relationship matrices\n' +
      '- **Infographic (infographic)**: Suitable for showing data visualization, information presentation, creative charts\n' +
      '## Selection Guide\n' +
      '1. Analyze the core content and objectives of the user\'s requirements\n' +
      '2. Select the chart type(s) that can most clearly express the information\n' +
      '3. If a specific chart type is selected, strictly follow the visual specifications for that type\n' +
      '4. Ensure the chart can independently convey information with a clear and attractive layout'
    );
  }

  // Add user input
  promptParts.push(`User requirements:\n${userInput}`);

  // Join all parts with double newlines for better readability
  return promptParts.join('\n\n');
};
